---
title: "D04"
author: "ekoh"
date: '2020 1 9 '
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data()
library(dplyr)
library(ggplot2)
data()

data("diamonds")
str(diamonds)

diamonds %>%
  ggplot(aes(x = cut, y = price)) +
  geom_jitter()

# 막대그래프 작성
month <- 1:6
rain <- c(55,50,45,50,60,70)
df <- data.frame(month, rain)
df
d <- ggplot(mpg, aes(fl))
n <- d + geom_bar(aes(fill = fl))
df %>%
  ggplot(aes(x = month, y = rain)) +
  geom_bar(stat = "identity",
           fill = 'darkgreen')+
  theme_classic() +
  coord_flip()

# 히스토그램
ggplot(iris, aes(x = Petal.Length, fill = Species, color = Species)) +
  geom_histogram(binwidth = 0.5, na.rm = T)

# 산점도
iris %>%
  ggplot(aes(x=Petal.Length, y=Petal.Width,
             color = Sepal.Length,
             shape = Species,
             size = Sepal.Length)) +
  geom_point() +
  ggtitle("꽃잎의 길이와 폭") +
  theme(plot.title = element_text(size = 25, face = 'bold'),
        legend.position = "left")

# 상자그림
# alpha는 불투명도 조절절

diamonds %>%
  ggplot(aes(cut, price)) +
  geom_boxplot(aes(fill = cut, alpha = 0.3))
levels(diamonds$cut)


diamonds %>%
  mutate(cut = reorder(cut, price, median)) %>%
  ggplot(aes(cut, price)) +
  geom_boxplot(aes(fill = cut, alpha = 0.3))


# 2007년도 gapminder 데이터에서
# 국가별 평균소득과 기대수명, 그리고 대륙별 인구 수를
# 그래프로 나타내십시오.

library(gapminder)
str(gapminder)

gapminder %>%
  filter(year == 2007) %>%
  ggplot(aes(x = gdpPercap, y = lifeExp)) +
  geom_point(aes(size = pop, shape = continent)) + 
  scale_x_log10()

gapminder %>%
  filter(year == 2007) %>%
  ggplot(aes(x = continent, y = pop, fill = continent)) +
  geom_bar(stat = 'identity')


# mpg 데이터에서 자동차 등급(class)과
# 고속도로 주행연비(hwy)의 관계를
# 산점도와 상자그림으로 나타내시오.
str(mpg)

mpg %>%
  mutate(class = reorder(class, hwy, median)) %>%
  ggplot(aes(class, hwy)) +
  geom_point(aes(size = 3, col = class))

mpg %>%
  mutate(class = reorder(class, hwy, median)) %>%
  ggplot(aes(class, hwy)) +
  geom_boxplot(aes(fill = class, alpha = 0.3))


mpg %>% select(class) %>% distinct()
lvl <- c("compact", "midsize", "suv", "2seater", "minivan", "pickup", "subcompact")
mpg %>%
  mutate(class = factor(class, levels = lvl)) %>%
  ggplot(aes(class, hwy)) +
  geom_jitter(aes(col = class)) + 
  geom_boxplot(aes(fill = class, alpha = 0.3)) +
  theme_dark()


# 이상치 제거하고 boxplot
str(mpg)
mpg.compact <-
  mpg %>%
    filter(class == "compact")

(q <- quantile(mpg.compact$hwy))
q1 <- q[2]
q3 <- q[4]
iqr <- q3 - q1

mpg.compact %>%
  filter(hwy <= q3 + 1.5 * iqr &
           hwy >= q1 - 1.5 * iqr) %>%
  ggplot(aes(class, hwy)) +
  geom_jitter(aes(col = class)) + 
  geom_boxplot(aes(fill = class, alpha = 0.3))


# 라인그래프 - 연도별 기대수명
str(gapminder)
summary(gapminder$year)

gapminder %>%
  filter(grepl("korea, re", country, ignore.case = T)) %>%
  ggplot(aes(year, lifeExp)) +
  geom_point() +
  geom_line(lwd = 3)

gapminder %>%
  ggplot(aes(year, lifeExp, 
             group = country, col = continent)) +
  geom_line() +
  facet_wrap( ~ continent)

gapminder %>%
  filter(continent == "Oceania")%>%
  ggplot(aes(year, lifeExp)) +
  geom_line(aes(color = country))
```

